<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RideRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RideRepository extends EntityRepository
{
    public function findNotFinishedRides($uuid)
    {
        $qb = $this->createQueryBuilder('r')
            ->andWhere('r.uuid = :uuid')
            ->andWhere('r.endTime is null');

        return $qb->setParameter(':uuid', $uuid)
            ->getQuery()
            ->execute();
    }
}
