<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RideRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RideRepository extends EntityRepository
{
}
